[package]
name = "saka-nes-simulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
bitfield = "0.12.0"